### ISSUE TITLE
Document how to verify timestamp using openssl?

### ISSUE THREAD

**Issue by petterreinholdtsen** [trbs/rfc3161ng#10]
When using openssl ts with tsget to fetch a trusted timestamp, one can use this command to verifty the signature:

  openssl ts -verify -data "<hash>" -in "<resultfile>" -CAfile "<certificatefile>"

Do you know how to process the result from this python library to be able to verify the timestamp using openssl?  If so, could you please document it in the README?

**Comment by trbs** [comment]
please check 4cfb5c78e77bac790ecde4cff90018fc6db2bf3a is that what you where thinking of ?

**Comment by petterreinholdtsen** [comment]
Yes, that was exactly the process I was wondering about.  I plan to store the timestamps in a database/archive, and want to know how the users of the future can validate them using simple command line tools like openssl.

If this process is documented, for example in the README, I would be very happy. :)

**Comment by trbs** [comment]
Regretfully `return_tsr=True` is a bit of a hack, would be better to spend some time creating better objects / interfaces, but this all started out just to have a working Python 3 library :-) (and secondly to also support the server part of rfc3161)

In your case it might be even better to store the raw `response.content` in the database. Since with `return_tsr=True` we are basically decoding and re-encoding the response from the server. Both will work.

Would you mind writing an example in the README based on the test case ?

**Comment by trbs** [comment]
If you have suggestions to improve the documentation in the README please submit a PR 👍
